### PR TITLE
fix: version 2 on rda files #9

### PR DESCRIPTION
**Pull request by laresbernardo**

### CODE REVIEW

**Comment by laresbernardo** [comment]
Checks failed, independent of this merge

**Comment by datawookie** [comment]
@laresbernardo this is why the tests failed on your PR:

image

**Comment by laresbernardo** [comment]
Makes sense. Maybe we could use the demo credentials for the tests and examples by default? Not the best practices but set default `"BINANCE_API_KEY"` and `"BINANCE_API_SECRET"` on load with the demo API credentials?

**Comment by datawookie** [comment]
Are you suggesting hard-coding those credentials into the test files?

**Pull request merged**
